name: base
description: "基础模块"
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

publish_to: none  # 添加这一行，否会使用本地宝会有警告提示
resolution: workspace  # 使用 workspace 统一管理依赖

dependencies:
  flutter:
    sdk: flutter

  # 第三方依赖（版本由根 workspace 统一管理）
  # 网络相关-------------------------------------
  json_annotation:
  retrofit:
  # 网络请求 用了retrofit无需使用以下方法
  #dio:
  # RxJava
  rxdart:
  #加解密
  encrypt:

  # 文件相关---------------------------------------
  #图片选择
  image_picker:
  # 保存图片到相册 仅支持Android IOS 其他平台需要编写兼容性方案
  image_gallery_saver_plus:
  # 文件选择
  file_picker:
  # 路径访问
  path_provider:
  # 打开文件
  open_file:
  # url_launcher
  url_launcher:

  # Workspace 内的本地包
  fast:
  db_base:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  # 网络相关-------------------------------------
  retrofit_generator:
  #json_serializable 生成新的命令 flutter pub run build_runner build
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/