name: auth
description: "认证库"
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace  # 使用 workspace 统一管理依赖

dependencies:
  flutter:
    sdk: flutter

  # Workspace 内的本地包
  fast:
  db_base:
  bizapi:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  # 网络相关-------------------------------------
  retrofit_generator:
  #json_serializable 生成新的命令 flutter pub run build_runner build
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true